(function(){'use strict';
const H=window.HozTools,$=H.$,t=H.tr;
let dialog,video,fileInput,statusEl,resultBox,resultValue,openResultBtn,stream=null,detector=null,raf=0,lastScan=0,detecting=false,current='',facing='environment',torchOn=false,switchingCamera=false;
const icon=n=>`<span class="action-glyph" aria-hidden="true">${H.icon(n)}</span>`;
function build(){
 if(dialog)return;
 dialog=document.createElement('dialog');dialog.id='qrReaderDialog';dialog.className='qr-reader-dialog';
 dialog.innerHTML=`<section class="qr-reader-sheet"><header class="qr-reader-head"><div class="qr-reader-heading"><span class="qr-reader-heading-icon" aria-hidden="true">${H.icon('ScanEye')}</span><div class="qr-reader-copy"><small data-en="QR reader" data-ar="قارئ QR" data-es="Lector QR">QR reader</small><h2 data-en="Scan a QR code" data-ar="اقرأ رمز QR" data-es="Escanear un código QR">Scan a QR code</h2></div></div><button id="qrReaderClose" class="qr-reader-close" type="button" aria-label="Close">${H.icon('X')}</button></header><div class="qr-reader-body"><div class="qr-reader-actions"><button id="qrCameraBtn" class="btn primary" type="button">${icon('ScanEye')}<span data-en="Open camera" data-ar="فتح الكاميرا" data-es="Abrir cámara">Open camera</span></button><button id="qrImageBtn" class="btn cyan" type="button">${icon('Image')}<span data-en="Choose image" data-ar="اختيار صورة" data-es="Elegir imagen">Choose image</span></button><input id="qrReaderFile" class="qr-reader-file" type="file" accept="image/*" data-native-file></div><p class="qr-reader-note" data-en="Scanning happens on this device. The camera feed and selected image are never uploaded." data-ar="تتم القراءة على جهازك. لا تُرفع الكاميرا أو الصورة المختارة إلى أي خادم." data-es="La lectura ocurre en tu dispositivo. La cámara y la imagen elegida nunca se suben.">Scanning happens on this device. The camera feed and selected image are never uploaded.</p><div id="qrCameraStage" class="qr-camera-stage" hidden><video id="qrReaderVideo" playsinline muted autoplay></video><div class="qr-scan-frame"><span class="qr-scan-line"></span></div><div class="qr-camera-controls" role="group" aria-label="Camera controls"><button id="qrFlipCamera" class="qr-camera-control" type="button" disabled>${H.icon('RefreshCw')}<span data-en="Flip" data-ar="قلب" data-es="Girar">Flip</span></button><button id="qrTorchBtn" class="qr-camera-control" type="button" aria-pressed="false" disabled>${H.icon('Sparkles')}<span data-en="Flash" data-ar="فلاش" data-es="Flash">Flash</span></button></div></div><p id="qrReaderStatus" class="qr-reader-status" role="status" aria-live="polite"></p><div id="qrReaderResult" class="qr-reader-result" hidden><small data-en="Detected content" data-ar="المحتوى المقروء" data-es="Contenido detectado">Detected content</small><pre id="qrReaderValue" class="qr-reader-value" dir="auto"></pre><div class="qr-reader-result-actions"><button id="qrReaderCopy" class="btn ghost" type="button">${icon('Copy')}<span data-en="Copy" data-ar="نسخ" data-es="Copiar">Copy</span></button><a id="qrReaderOpen" class="btn ghost" href="#" target="_blank" rel="noopener noreferrer" hidden>${icon('ExternalLink')}<span data-en="Open" data-ar="فتح" data-es="Abrir">Open</span></a><button id="qrReaderUse" class="btn mint" type="button">${icon('QrCode')}<span data-en="Use in generator" data-ar="استخدامه في المولد" data-es="Usar en el generador">Use in generator</span></button></div></div></div></section>`;
 document.body.append(dialog);video=$('#qrReaderVideo',dialog);fileInput=$('#qrReaderFile',dialog);statusEl=$('#qrReaderStatus',dialog);resultBox=$('#qrReaderResult',dialog);resultValue=$('#qrReaderValue',dialog);openResultBtn=$('#qrReaderOpen',dialog);
 $('#qrReaderClose',dialog).onclick=()=>dialog.close();$('#qrCameraBtn',dialog).onclick=()=>startCamera();$('#qrImageBtn',dialog).onclick=()=>fileInput.click();$('#qrFlipCamera',dialog).onclick=flipCamera;$('#qrTorchBtn',dialog).onclick=toggleTorch;fileInput.onchange=()=>{const f=fileInput.files?.[0];if(f)scanImage(f);fileInput.value=''};$('#qrReaderCopy',dialog).onclick=()=>H.copy(current);$('#qrReaderUse',dialog).onclick=useInGenerator;
 dialog.addEventListener('close',()=>{stopCamera();reset(false)});dialog.addEventListener('click',e=>{if(e.target===dialog)dialog.close()});document.addEventListener('hoz:language',localizeDialog);localizeDialog();
}
function localizeDialog(){if(!dialog)return;dialog.querySelectorAll('[data-en]').forEach(el=>{const v=el.dataset[H.lang()];if(v!=null)el.textContent=v});$('#qrReaderClose',dialog)?.setAttribute('aria-label',t('Close','إغلاق','Cerrar'));$('#qrFlipCamera',dialog)?.setAttribute('aria-label',t('Switch camera','تبديل الكاميرا','Cambiar cámara'));$('#qrTorchBtn',dialog)?.setAttribute('aria-label',torchOn?t('Turn flash off','إيقاف الفلاش','Apagar flash'):t('Turn flash on','تشغيل الفلاش','Encender flash'));$('.qr-camera-controls',dialog)?.setAttribute('aria-label',t('Camera controls','عناصر تحكم الكاميرا','Controles de cámara'));if(!current&&!stream)setStatus(t('Choose the camera or an image to read a QR code.','اختر الكاميرا أو صورة لقراءة رمز QR.','Elige la cámara o una imagen para leer un QR.'),'idle')}
function reset(clear=true){if(clear){current='';resultBox.hidden=true;resultValue.textContent='';openResultBtn.hidden=true;openResultBtn.removeAttribute('href')}const stage=$('#qrCameraStage',dialog);if(stage)stage.hidden=true;if(clear)setStatus(t('Choose the camera or an image to read a QR code.','اختر الكاميرا أو صورة لقراءة رمز QR.','Elige la cámara o una imagen para leer un QR.'),'idle')}
function setStatus(message,state='idle'){statusEl.textContent=message;statusEl.dataset.state=state}
async function getDetector(){if(detector)return detector;if(!('BarcodeDetector' in globalThis))throw Error(t('QR reading is not supported by this browser. Use a current Chrome or Samsung Internet on Android.','قراءة QR غير مدعومة في هذا المتصفح. استخدم إصدارًا حديثًا من Chrome أو Samsung Internet على أندرويد.','Este navegador no admite la lectura QR. Usa Chrome o Samsung Internet actualizado en Android.'));try{const formats=BarcodeDetector.getSupportedFormats?await BarcodeDetector.getSupportedFormats():['qr_code'];if(formats.length&&!formats.includes('qr_code'))throw Error();detector=new BarcodeDetector({formats:['qr_code']});return detector}catch{throw Error(t('This browser cannot detect QR codes.','هذا المتصفح لا يستطيع قراءة رموز QR.','Este navegador no puede detectar códigos QR.'))}}
function safeLink(value){try{const u=new URL(value);return ['http:','https:','mailto:','tel:','sms:','geo:'].includes(u.protocol)?u.href:''}catch{return''}}
function showResult(value){current=String(value||'').trim();if(!current)return false;resultValue.textContent=current;resultBox.hidden=false;const href=safeLink(current);openResultBtn.hidden=!href;if(href)openResultBtn.href=href;setStatus(t('QR code read successfully.','تمت قراءة رمز QR بنجاح.','Código QR leído correctamente.'),'ready');resultBox.scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'auto':'smooth',block:'nearest'});return true}
async function startCamera(targetFacing=facing,{clear=true,quiet=false}={}){if(clear)reset();stopCamera();try{await getDetector();if(!navigator.mediaDevices?.getUserMedia)throw Error(t('Camera access is not available in this browser.','الوصول إلى الكاميرا غير متاح في هذا المتصفح.','El acceso a la cámara no está disponible.'));if(!quiet)setStatus(t('Requesting camera access…','جارٍ طلب إذن الكاميرا…','Solicitando acceso a la cámara…'));const next=await navigator.mediaDevices.getUserMedia({audio:false,video:{facingMode:{ideal:targetFacing},width:{ideal:1280},height:{ideal:960}}});stream=next;const track=stream.getVideoTracks()[0];const actual=track?.getSettings?.().facingMode;facing=actual==='user'||actual==='environment'?actual:targetFacing;video.srcObject=stream;video.classList.toggle('is-front-camera',facing==='user');await video.play();$('#qrCameraStage',dialog).hidden=false;updateCameraControls();setStatus(t('Point the camera at the QR code.','وجّه الكاميرا نحو رمز QR.','Apunta la cámara al código QR.'));raf=requestAnimationFrame(scanLoop);return true}catch(e){stopCamera();setStatus(e.name==='NotAllowedError'?t('Camera permission was denied. You can choose an image instead.','تم رفض إذن الكاميرا. يمكنك اختيار صورة بدلًا من ذلك.','Se denegó el permiso de cámara. Puedes elegir una imagen.'):e.message,'error');return false}}
async function scanLoop(ts){if(!stream||!dialog.open)return;if(ts-lastScan>180&&!detecting&&video.readyState>=2){detecting=true;lastScan=ts;try{const codes=await detector.detect(video);if(codes?.[0]?.rawValue&&showResult(codes[0].rawValue)){stopCamera();return}}catch{}finally{detecting=false}}raf=requestAnimationFrame(scanLoop)}
function cameraTrack(){return stream?.getVideoTracks?.()[0]||null}
function updateCameraControls(){if(!dialog)return;const flip=$('#qrFlipCamera',dialog),torch=$('#qrTorchBtn',dialog),track=cameraTrack(),caps=track?.getCapabilities?.()||{};if(flip)flip.disabled=!track||switchingCamera;if(torch){const supported=!!caps.torch;torch.disabled=!track||!supported;torch.classList.toggle('is-active',supported&&torchOn);torch.setAttribute('aria-pressed',String(supported&&torchOn));torch.title=supported?'':t('Flash is not supported by this camera.','الفلاش غير مدعوم في هذه الكاميرا.','El flash no está disponible en esta cámara.')}localizeDialog()}
async function flipCamera(){if(!cameraTrack()||switchingCamera)return;switchingCamera=true;updateCameraControls();const previous=facing,next=previous==='environment'?'user':'environment';setStatus(t('Switching camera…','جارٍ تبديل الكاميرا…','Cambiando cámara…'));const ok=await startCamera(next,{clear:false,quiet:true});if(!ok){H.toast(t('Could not switch camera. Restoring the previous camera.','تعذّر تبديل الكاميرا. تتم استعادة الكاميرا السابقة.','No se pudo cambiar de cámara. Restaurando la anterior.'),'error');await startCamera(previous,{clear:false,quiet:true})}switchingCamera=false;updateCameraControls()}
async function toggleTorch(){const track=cameraTrack(),caps=track?.getCapabilities?.()||{};if(!track||!caps.torch){H.toast(t('Flash is not supported by this camera.','الفلاش غير مدعوم في هذه الكاميرا.','El flash no está disponible en esta cámara.'),'error');return}const next=!torchOn;try{await track.applyConstraints({advanced:[{torch:next}]});torchOn=next;updateCameraControls();setStatus(next?t('Flash turned on. Point the camera at the QR code.','تم تشغيل الفلاش. وجّه الكاميرا نحو رمز QR.','Flash encendido. Apunta la cámara al código QR.'):t('Flash turned off. Point the camera at the QR code.','تم إيقاف الفلاش. وجّه الكاميرا نحو رمز QR.','Flash apagado. Apunta la cámara al código QR.'))}catch{torchOn=false;updateCameraControls();H.toast(t('The camera could not change the flash state.','تعذّر تغيير حالة الفلاش في الكاميرا.','La cámara no pudo cambiar el estado del flash.'),'error')}}
function stopCamera(){cancelAnimationFrame(raf);raf=0;torchOn=false;if(stream){stream.getTracks().forEach(track=>track.stop());stream=null}if(video){video.pause();video.srcObject=null;video.classList.remove('is-front-camera')}const stage=dialog&&$('#qrCameraStage',dialog);if(stage)stage.hidden=true;updateCameraControls()}
async function scanImage(file){reset();stopCamera();try{if(!file.type.startsWith('image/'))throw Error(t('Choose an image file.','اختر ملف صورة.','Elige un archivo de imagen.'));if(file.size>25*1024*1024)throw Error(t('Choose an image smaller than 25 MB.','اختر صورة أصغر من 25 ميجابايت.','Elige una imagen menor de 25 MB.'));const d=await getDetector();setStatus(t('Reading the image…','جارٍ قراءة الصورة…','Leyendo la imagen…'));let source;if('createImageBitmap' in globalThis)source=await createImageBitmap(file);else{source=new Image();source.src=URL.createObjectURL(file);await source.decode()}try{const codes=await d.detect(source);if(!codes?.length)throw Error(t('No readable QR code was found in this image.','لم يتم العثور على رمز QR قابل للقراءة في هذه الصورة.','No se encontró un código QR legible en esta imagen.'));showResult(codes[0].rawValue)}finally{source?.close?.();if(source instanceof HTMLImageElement)URL.revokeObjectURL(source.src)}}catch(e){setStatus(e.message,'error')}}
function useInGenerator(){if(!current)return;const type=$('#qrType');if(/^https?:\/\//i.test(current)){type.value='url';type.dispatchEvent(new Event('change',{bubbles:true}));$('#urlValue').value=current;$('#urlValue').dispatchEvent(new Event('input',{bubbles:true}))}else{type.value='text';type.dispatchEvent(new Event('change',{bubbles:true}));$('#textValue').value=current;$('#textValue').dispatchEvent(new Event('input',{bubbles:true}))}dialog.close();$('#generateBtn')?.scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'auto':'smooth',block:'center'});H.toast(t('QR content added to the generator.','تمت إضافة محتوى QR إلى المولد.','Contenido QR añadido al generador.'))}
function openReader(){build();reset();dialog.showModal();setTimeout(()=>$('#qrCameraBtn',dialog)?.focus(),30)}
document.addEventListener('DOMContentLoaded',()=>{build();const trigger=$('#qrReaderBtn');if(trigger)trigger.addEventListener('click',openReader)});
})();
