(function(){'use strict';const H=window.HozTools,$=H.$,$$=H.$$;let qr=null,data='',logoData='';const t=(en,ar,es)=>({en,ar,es}[H.lang()]);
function esc(v){return String(v||'').replace(/([\\;,:"])/g,'\\$1')}
function value(){const k=$('#qrType').value,q=encodeURIComponent;if(k==='url')return $('#urlValue').value.trim();if(k==='text')return $('#textValue').value;if(k==='wifi')return`WIFI:T:${$('#wifiSecurity').value};S:${esc($('#wifiName').value)};P:${esc($('#wifiPass').value)};H:${$('#wifiHidden').checked?'true':'false'};;`;if(k==='whatsapp')return`https://wa.me/${H.phone($('#waCode').value,$('#waNumber').value)}?text=${q($('#waMessage').value)}`;if(k==='phone')return'tel:'+$('#phoneValue').value.replace(/\s/g,'');if(k==='sms')return`sms:${$('#smsPhone').value}?body=${q($('#smsMessage').value)}`;if(k==='email')return`mailto:${$('#emailTo').value}?subject=${q($('#emailSubject').value)}&body=${q($('#emailBody').value)}`;if(k==='location')return`geo:${$('#latitude').value},${$('#longitude').value}`;if(k==='telegram')return'https://t.me/'+$('#telegramUser').value.replace(/^@/,'');if(k==='instagram')return'https://instagram.com/'+$('#instagramUser').value.replace(/^@/,'');if(k==='crypto')return`${$('#cryptoScheme').value}:${$('#cryptoAddress').value.trim()}`;if(k==='vcard')return`BEGIN:VCARD\nVERSION:3.0\nFN:${esc($('#vName').value)}\nORG:${esc($('#vCompany').value)}\nTEL:${esc($('#vPhone').value)}\nEMAIL:${esc($('#vEmail').value)}\nURL:${esc($('#vUrl').value)}\nEND:VCARD`;if(k==='event'){const dt=v=>v?new Date(v).toISOString().replace(/[-:]/g,'').replace(/\.\d{3}/,''):'';return`BEGIN:VEVENT\nSUMMARY:${esc($('#eventTitle').value)}\nDTSTART:${dt($('#eventStart').value)}\nDTEND:${dt($('#eventEnd').value)}\nLOCATION:${esc($('#eventLocation').value)}\nEND:VEVENT`}return''}
function validate(){
const kind=$('#qrType').value,required={url:['urlValue'],text:['textValue'],wifi:['wifiName'],phone:['phoneValue'],sms:['smsPhone'],email:['emailTo'],location:['latitude','longitude'],telegram:['telegramUser'],instagram:['instagramUser'],crypto:['cryptoAddress'],vcard:['vName'],event:['eventTitle','eventStart','eventEnd']};
const fail=()=>{throw Error(t('Check the required fields and their format.','راجع الحقول المطلوبة وصحة بياناتها.','Revisa los campos obligatorios y su formato.'))};
for(const id of required[kind]||[])if(!$('#'+id).value.trim())fail();
if(kind==='url'){try{const u=new URL($('#urlValue').value.trim());if(!['http:','https:'].includes(u.protocol))fail()}catch{fail()}}
if(kind==='email'&&!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test($('#emailTo').value.trim()))fail();
if(kind==='location'){const lat=Number($('#latitude').value),lon=Number($('#longitude').value);if(!Number.isFinite(lat)||!Number.isFinite(lon)||Math.abs(lat)>90||Math.abs(lon)>180)fail()}
if(kind==='event'&&new Date($('#eventEnd').value)<=new Date($('#eventStart').value))fail();
if(kind==='wifi'&&$('#wifiSecurity').value!=='nopass'&&!$('#wifiPass').value)fail();
}
function options(){const size=+$('#qrSize').value;if($('#foreground').value===$('#background').value)throw Error(t('Choose contrasting colors.','اختر لونين متباينين.','Elige colores con contraste.'));return{width:size,height:size,type:'svg',data,image:logoData||undefined,margin:18,qrOptions:{errorCorrectionLevel:logoData?'H':$('#errorLevel').value},dotsOptions:{color:$('#foreground').value,type:$('#dots').value},backgroundOptions:{color:$('#background').value},cornersSquareOptions:{color:$('#foreground').value,type:$('#corners').value},cornersDotOptions:{color:$('#foreground').value,type:$('#corners').value==='dot'?'dot':'square'},imageOptions:{crossOrigin:'anonymous',margin:8,imageSize:.35}}}
function generate(){validate();data=value();if(!data)return H.toast(t('Enter content first','أدخل المحتوى أولًا','Introduce el contenido'),'error');if(!window.QRCodeStyling)return H.toast(t('QR engine did not load. Check your connection.','لم يُحمّل محرك QR. تحقق من اتصالك.','El motor QR no se ha cargado.'),'error');const box=$('#qrPreview');box.innerHTML='';qr=new QRCodeStyling(options());qr.append(box);['pngBtn','svgBtn','copyData','shareBtn'].forEach(id=>$('#'+id).disabled=false)}
function refresh(){if(qr)try{qr.update(options())}catch(e){H.toast(e.message,'error')}}
$('#qrType').onchange=()=>{$$('.qr-fields').forEach(x=>x.classList.toggle('hidden',x.dataset.kind!==$('#qrType').value))};$('#generateBtn').onclick=()=>H.busy($('#generateBtn'),generate);['dots','corners','foreground','background','qrSize','errorLevel'].forEach(id=>$('#'+id).addEventListener('input',refresh));$('#pngBtn').onclick=()=>qr?.download({name:'hoztools-qr',extension:'png'});$('#svgBtn').onclick=()=>qr?.download({name:'hoztools-qr',extension:'svg'});$('#copyData').onclick=()=>H.copy(data);$('#shareBtn').onclick=()=>navigator.share?navigator.share({title:'QR',text:data}).catch(()=>{}):H.copy(data);$('#logo').onchange=e=>{const f=e.target.files[0];if(!f){logoData='';return refresh()}if(f.size>2e6||!/^image\/(png|jpeg|webp|gif)$/.test(f.type))return H.toast(t('Use an image logo below 2 MB.','استخدم شعار صورة دون 2 ميجابايت.','Usa un logotipo menor de 2 MB.'),'error');const r=new FileReader();r.onload=()=>{logoData=r.result;refresh()};r.readAsDataURL(f)};window.addEventListener('load',()=>$('#engineStatus').textContent=window.QRCodeStyling?t('Ready','جاهز','Listo'):t('Unavailable','غير متاح','No disponible'));
function stale(){qr=null;data='';$('#qrPreview').replaceChildren();['pngBtn','svgBtn','copyData','shareBtn'].forEach(id=>$('#'+id).disabled=true)}$$('#dynamicFields input,#dynamicFields textarea,#dynamicFields select').forEach(el=>el.addEventListener('input',stale));$('#qrType').addEventListener('change',stale);
})();
