(function(){'use strict';const H=window.HozTools,$=H.$,$$=H.$$;let mode='password',values=[];const sets={lower:'abcdefghijklmnopqrstuvwxyz',upper:'ABCDEFGHIJKLMNOPQRSTUVWXYZ',numbers:'0123456789',symbols:'!@#$%^&*()-_=+[]{};:,.?'};const words=['amber','atlas','bamboo','beacon','breeze','cairo','cedar','cobalt','comet','coral','cosmos','delta','desert','eagle','ember','falcon','forest','galaxy','garden','harbor','hazel','island','jasmine','lagoon','lemon','lunar','maple','meadow','mint','mosaic','nebula','oasis','olive','onyx','orbit','panda','pearl','phoenix','planet','quartz','raven','river','saffron','sahara','shadow','silver','solar','sparrow','stone','storm','summit','sunset','tiger','valley','velvet','violet','wave','willow','zephyr'];const t=(en,ar,es)=>({en,ar,es}[H.lang()]);
function rnd(max){if(max<=0)throw Error('range');const lim=0x100000000-(0x100000000%max),a=new Uint32Array(1);do{crypto.getRandomValues(a)}while(a[0]>=lim);return a[0]%max}
function shuffle(a){for(let i=a.length-1;i>0;i--){const j=rnd(i+1);[a[i],a[j]]=[a[j],a[i]]}return a}
function password(){let groups=[];['lower','upper','numbers','symbols'].forEach(k=>{if($('#'+k).checked)groups.push($('#ambiguous').checked?sets[k].replace(/[0O1Il|]/g,''):sets[k])});if(!groups.length)throw Error('sets');let pool=groups.join('');const len=+$('#length').value,res=groups.map(g=>g[rnd(g.length)]);while(res.length<len)res.push(pool[rnd(pool.length)]);return shuffle(res).join('')}
function phrase(){const count=+$('#wordCount').value,sep=$('#separator').value,cap=$('#capitalization').value,p=[];for(let i=0;i<count;i++){let w=words[rnd(words.length)];if(cap==='title'||(cap==='random'&&rnd(2)))w=w[0].toUpperCase()+w.slice(1);p.push(w)}let out=p.join(sep);if($('#addNumber').checked)out+=sep+(10+rnd(90));return out}
function generate(){try{values=[];const q=mode==='password'?+$('#quantity').value:1;for(let i=0;i<q;i++)values.push(mode==='password'?password():phrase());render();$('#strength').removeAttribute('data-stale');$('#copyAll').disabled=false}catch{values=[];$('#results').textContent='';$('#copyAll').disabled=true;H.toast(t('Choose at least one character group','اختر مجموعة أحرف واحدة على الأقل','Elige al menos un grupo de caracteres'),'error')}}
function render(){const v=values[0],pool=['lower','upper','numbers','symbols'].filter(k=>$('#'+k).checked).reduce((n,k)=>n+($('#ambiguous').checked?sets[k].replace(/[0O1Il|]/g,''):sets[k]).length,0),entropy=mode==='password'?Math.floor((v.length-['lower','upper','numbers','symbols'].filter(k=>$('#'+k).checked).length)*Math.log2(pool||1)):Math.round((+$('#wordCount').value)*Math.log2(words.length)+($('#addNumber').checked?6.5:0)),label=entropy>=100?t('Excellent','ممتازة','Excelente'):entropy>=70?t('Strong','قوية','Fuerte'):entropy>=45?t('Fair','متوسطة','Aceptable'):t('Weak','ضعيفة','Débil');$('#strength').innerHTML=`<strong class="big">${label}</strong><span class="muted">≈ ${entropy} ${t('bits of entropy','بت من العشوائية','bits de entropía')}</span>`;$('#results').innerHTML=values.map((x,i)=>`<div class="list-row"><code class="grow mono truncate" title="${H.esc(x)}">${H.esc(x)}</code><button class="btn small ghost" data-copy="${i}">${t('Copy','نسخ','Copiar')}</button></div>`).join('');$$('[data-copy]').forEach(b=>b.onclick=()=>H.copy(values[+b.dataset.copy]))}
document.addEventListener('hoz:tab',e=>{mode=e.detail;generate()});document.addEventListener('hoz:language',()=>{if(values.length)render()});$('#wordCount').min='8';$('#wordCount').max='16';$('#wordCount').value='12';const syncWordCount=()=>{const el=$('#wordCountLabel');if(el)el.textContent=$('#wordCount').value};$('#length').oninput=()=>$('#lengthLabel').textContent=$('#length').value;$('#wordCount').oninput=()=>{syncWordCount();if(mode==='passphrase')generate()};syncWordCount();$('main').addEventListener('input',e=>{if(e.target.closest('#results'))return;values=[];$('#results').replaceChildren();$('#strength').textContent=t('Settings updated. Generate a new password.','تغيّرت الإعدادات. ولّد كلمة مرور جديدة.','Ajustes actualizados. Genera una contraseña nueva.');$('#copyAll').disabled=true});$('#generate').onclick=generate;$('#copyAll').onclick=()=>H.copy(values.join('\n'));generate();
})();
